---
#- name: update dnf repo
#  package: name=* state=latest
  
- name: install the 'Development tools' package group
  package: name="@Development tools" state=present
  tags:
    - dev
   
- name: install every thing
  package: name="meld,keepass,vim,maven" state=present
  tags:
   - dev

- name: Download Oracle JDK
  get_url: 
    url=http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz 
    headers=Cookie:oraclelicense=accept-securebackup-cookie
    validate_certs=false
    dest=/opt/developer/jdk-8u111-linux-x64.tar.gz
    owner={{ user}}
    group={{ user}}
  tags:
   - dev
   - oracle

- name: Extract Oracle
  unarchive: 
    src=/opt/developer/jdk-8u111-linux-x64.tar.gz 
    dest=/opt/developer/
    creates=/opt/developer/jdk1.8.0_111/
    owner={{ user}}
    group={{ user}}
  tags:
   - dev
   - oracle

- name: Create JDK Links
  file: src=/opt/developer/jdk1.8.0_111 dest=/opt/developer/jdk state=link
    owner={{ user}}
    group={{ user}}
  tags:
   - dev
   - oracle

- name: Download Wildfly
  get_url: 
    url=http://download.jboss.org/wildfly/10.0.0.Final/wildfly-10.0.0.Final.tar.gz 
    dest=/opt/developer/wildfly-10.0.0.Final.tar.gz
    owner={{ user}}
    group={{ user}}
  tags:
   - dev
   - wildfly

- name: Extract Wildfly
  unarchive: 
    src=/opt/developer/wildfly-10.0.0.Final.tar.gz 
    dest=/opt/developer/
    creates=/opt/developer/wildfly-10.0.0.Final/
    owner={{ user}}
    group={{ user}}
  tags:
   - dev
   - wildfly

- name: Create Wildfly Links
  file: src=/opt/developer/wildfly-10.0.0.Final dest=/opt/developer/wildfly state=link
    owner={{ user}}
    group={{ user}}
  tags:
   - dev
   - wildfly
   
- name: Download Eclipse
  get_url: 
    url=http://mirror.csclub.uwaterloo.ca/eclipse/technology/epp/downloads/release/neon/1a/eclipse-jee-neon-1a-linux-gtk-x86_64.tar.gz
    dest=/opt/developer/eclipse-inst-linux64.tar.gz
    owner={{ user}}
    group={{ user}}
  tags:
   - dev
   - eclipse

- name: Extract Eclipse
  unarchive: 
    src=/opt/developer/eclipse-inst-linux64.tar.gz
    dest=/opt/developer/
    creates=/opt/developer/eclipse/
    owner={{ user}}
    group={{ user}}
  tags:
   - dev
   - eclipse

- name: Download Android Studio
  get_url: 
    url=https://dl.google.com/dl/android/studio/ide-zips/2.2.2.0/android-studio-ide-145.3360264-linux.zip
    dest=/opt/developer/android-studio-ide-145.3360264-linux.zip
    owner={{ user}}
    group={{ user}}
  tags:
   - dev
   - android

- name: Extract Android Studio
  unarchive: 
    src=/opt/developer/android-studio-ide-145.3360264-linux.zip
    dest=/opt/developer/
    creates=/opt/developer/android-studio/
    owner={{ user}}
    group={{ user}}
  tags:
   - dev
   - android

#maven settings
#gimp
#blender
#npm
#Three.js

