---
- name: Copy Files For Home Directory
  copy:
   src={{ item }}
   dest=~{{user}}/.{{ item }}
   owner={{user}}
   group={{user}}
  with_items:
   - vimrc
   - bashrc
   - bash_profile
   - bash_profile.d/
   - bashrc.d/
   - m2
  tags:
   - home
