---
#TODO copy ~/cots stuff to /usr/share
#TODO set correct download path
#TODO Setup wildfly as a service

- name: Download Wildfly
  get_url: url=http://download.jboss.org/wildfly/10.0.0.Final/wildfly-10.0.0.Final.tar.gz dest=/opt/wildfly-10.0.0.Final.tar.gz
    
- name: Extract archive
  unarchive: src=/opt/wildfly-10.0.0.Final.tar.gz dest=/opt/

- name: Copy the init script
  copy: src=wildfly-init-redhat.sh dest=/etc/init.d/wildfly mode=0755

- name: Copy the config script
  template: src=wildfly.conf dest=/etc/default/wildfly.conf mode=0755
  
#- name: Enable JBoss to be started at boot
#  service: name=wildfly enabled=yes state=started 
  
